---
title: "About Me"
---

# Education Experience

## Programs:Mathematics and Statistics

## College: New College

## Year of Graduate: 2025

# Personal Skills

## Language: English (Fluent); Mandarin (Native); Thai (Basic)

## Skills: RStudio, Microsoft Office, Canva, Python (Basic), Extensive experience in poster design, Excellent drawing skills

# Project (Data Analysis)

## "Analysis of Daily Shelter Occupancy in Toronto"

### This project investigates the daily occupancy rates of shelters in Toronto with the aim of understanding the effectiveness of shelter utilization and improving Toronto's shelter system.

## "Gender Dynamics in Financial Decision-Making: Unveiling the Money Illusion Effect in Brazil"

### This project investigates gender differences in economic decision-making through a money illusion experiment conducted with 372 Brazilian participants. It aims to understand how men and women perceive financial risks and make choices under different economic scenarios.

[My CV](cv.pdf)
